### ISSUE TITLE
requirements.txt  能否提供一下

### ISSUE THREAD

**Issue by vTNT** [taoprogramer/AnsiblePower#1]

**Comment by vTNT** [comment]
还有一块就是关于建表的 models里面managed=False  默认都不能建表

**Comment by vTNT** [comment]
还有一块就是关于建表的 models里面managed=False  默认都不能建表

**Comment by taoprogramer** [comment]
1.添加了requirements.txt
2.感谢提醒，去掉了models.py里的manged=False

**Comment by vTNT** [comment]
好的  谢谢

**Comment by vTNT** [comment]
另外我建表是 出现了 表名重复情况  主要是那些系统权限表。

**Comment by taoprogramer** [comment]
重复建的表应该是AuthUser表吧，现在去掉了AuthUser model里的manged=False
