### ISSUE TITLE
ansible的play.py 修改过吗？

### ISSUE THREAD

**Issue by fallencliff** [taoprogramer/AnsiblePower#4]
看了你的源码，你的playbookcallback.py里面
    def v2_playbook_on_play_start(self, play):
        name_item = play.get_name().split(':')
        self.task_id = int(name_item[0])
        self.instance_type = name_item[1]
我发现play.get_name().split(':')默认不会返回你这里的task_id和instance_type， 是你在ansible的play.py里修改过？

**Comment by taoprogramer** [comment]
没有修改，我应该是把task_id和instance_type用冒号连接，作为play的name，最后在callback里再分隔。

**Comment by fallencliff** [comment]
看明白了，你的代码给我了很多启发，非常感谢

**Comment by taoprogramer** [comment]
不客气！
